### ISSUE TITLE
为什么TVBox不能使用M3U的直播源啦？

### ISSUE THREAD

**Issue by majiancy** [youshandefeiyang/live-Url#4]
从7月份开始玩TVBox，一直用肥羊精选的M3U liveURL IPTV直播源（Ftindy的百x通高码率源），很流畅很爽，手机和电视盒子都用这。但从上周开始电视端不能看IPTV直播了，我就切了接口里包含的直播，虽然慢且要切换很多次才能看，但凑活用。可手机端我忍不了，一直捣鼓，今天才发现好像各种M3U的直播源，TVBox都显示“频道列表为空”。是TVBox升级升坏了？还是啥情况。我用了三种TVBox（白盒OSC，灰盒 和 Fongmi） 都试过，都不行。同样网络下，Win 10的Potplay可以访问对应的M3U。

**Comment by youshandefeiyang** [comment]
不清楚，没用过
